# What's the name of the church?
title: Bible Baptist Church
# Give a brief description of the church
description: > # this means to ignore newlines until "baseurl:"
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus blanditiis odio corrupti,
    illum architecto consequuntur, quaerat unde repudiandae qui temporibus! Fuga maxime molestiae hic impedit
    sit sint perferendis rerum unde.
# Leave this alone
baseurl: "" # the subpath of your site, e.g. /blog
# Change this to the domain when you are finished and ready to publish.

url: "http://adore-theme.pubstorm.site/" # the base hostname & protocol for your site | Switch to blistering-cheetah-217652.nitrousapp.com" Before running Glynn.  Afterwards change it back to http://localhost:4000/

# This is the path to the default images.  If you add different default images you can change them here.
default_header_image: "assets/default_header.jpg"
default_sermon_image: "assets/default_header.jpg"
default_blog_image: "assets/default_header.jpg"
default_about_image: "assets/default_header.jpg"
default_ministry_image: "assets/default_header.jpg"
default_calendar_image: "assets/calendar_default.jpg"


# Airtable API Stuff
airtable:
  apikey: "keyRTLlrVS02vC3Vx"
  blog: "appxF48xfkO7dHWGh"
  sermons: "apprDNNyNO4RHDP1q"
  series: "apprDNNyNO4RHDP1q"
  ministries: "appo4EmHX9KELKJ0u"
  photos: "appo4EmHX9KELKJ0u"
  events: "appo4EmHX9KELKJ0u"
  abouts: "appaVLGyitzv8N41y"
  slider: "appdR5OfLYCkzJh2Y"
  welcome: "appdKWpaSSSTcH3oN"
  info: "appWEk90aCD6aIerl"
  contact: "appcF6oP8OhXgbCio"
  missionaries: "appIfFWAjJoPWDoyp"
# LEAVE EVERYTHING ELSE ALONE!!

# Build settings
markdown: kramdown

# Exclude
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - bower_components
keep_files:
  - css


page_gen:
  - data: 'ministries'
    template: 'ministries'
    name: 'name'
    dir: 'ministries'
  - data: 'series'
    template: 'series'
    name: 'title'
    dir: 'series'
  - data: 'sermons'
    template: 'sermon'
    name: 'title'
    dir: 'sermons'
  - data: 'blog'
    template: 'blog-entry'
    name: 'title'
    dir: 'blog-posts'
  - data: 'abouts'
    template: 'aboutpage'
    name: 'title'
    dir: 'about-us'
  - data: 'events'
    template: 'event'
    name: 'event_name'
    dir: 'events'
  - data: 'abouts'
    template: 'about'
    name: 'title'
    dir: 'about-us'

ftp_host: 'biblebaptistmattoon.org'
ftp_dir: 'blessedhopemtvernon.org/'
ftp_passive: false
ftp_username: 'ryahay11'
ftp_password: '@88Volvocj'